id = "relm4-snippets"
name = "Relm4 Snippets"
version = "0.0.1"
schema_version = 1
authors = ["Eduardo Flores <edfloreshz@gmail.com>"]
description = "Relm4 code snippets"
repository = "https://github.com/Relm4/zed-relm4"

snippets = ["./snippets/rust.json"]
